insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Pol Valve Liquigaz', 'MLC', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Snap on Liquigaz', 'LC', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Island Gas', 'I', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('LPGMA', 'M', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Pryce Gas', 'P', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('LPGMA 5 KG', 'M5KG', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Island Gas 5 KG', 'I5KG', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('LPGMA 22 KG', 'M22KG', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Liquigaz 22 KG', 'MLC22KG', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('LPGMA 50 KG', 'M50KG', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Island Gas 50 KG', 'I50KG', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Pryce Gas 50 KG', 'P50KG', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Snap on Solane', 'S', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Pol Valve Solane', 'MS', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Snap on Gasul', 'G', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Pol Valve Gasul', 'MG', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Snap on Gasulito', 'GO', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Pol Valve Gasulito', 'MGO', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Gasulette', 'GE', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Gasulette with Regulator', 'MGE', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Shine Gas', 'SH', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Superkalan Gas', 'SK', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Wilkins', 'W', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Pol Valve Regulator', 'PVM', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Gasul Regulator', 'SOO', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Solane Regulator', 'AS', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Solane Regulator with Device', 'SO1', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Liquigaz Regulator', 'LCR', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Pol Valve Regulator (High Pressure)', 'HCR', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Hose Local', 'HSL', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Hose (High Pressure)', 'HPLH', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Gasket', 'GK', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Asbestos', 'ABS', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Throttle Knob', 'TN', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Clamp', 'CLP', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Bushing', 'BS', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Gasulette Adapter', 'GEA', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Y-Connector', 'YC', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('I-Connector', 'IC', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Gasulette Head Burner', 'GEHD', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Shine Head Burner', 'SHHD', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Shine Gas Handle', 'SHHDL', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Stove Burner', 'SB', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Single Burner (Standard)', 'SSB', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Double Burner (Standard)', 'SDB', now(), 1);
insert into item (itemName,	itemCode, creationDate,	dataEncoder) values ('Gas Stove (High Pressure)', 'HPGS', now(), 1);